task: detection

num_classes: 80
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: src/data/coco/train2017/
    ann_file: src/data/coco/annotations_trainval2017/annotations/instances_train2017.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 1
  num_workers: 0
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: src/data/coco/val2017/
    ann_file: src/data/coco/annotations_trainval2017/annotations/instances_val2017.json

    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 1
  num_workers: 0
  drop_last: False